### ISSUE TITLE
getting cid fails on bee 2.3.x

### ISSUE THREAD

**Issue by darkobas2** [ethersphere/swarm-actions#216]
```
Run ethersphere/swarm-actions/reference-to-cid@latest

/home/runner/work/_actions/ethersphere/swarm-actions/latest/node_modules/@ethersphere/swarm-cid/dist/index.js:160
        throw new TypeError(`${name} not valid hex string${lengthMsg}: ${s}`);
^
TypeError: value not valid hex string: {"reference":"a[9](https://github.com/fairDataSociety/fairdrive-landing-page/actions/runs/12380879860/job/34558194332#step:10:10)5c167f2a6e4198039dd86a220c65fce407f78378cf48e[10](https://github.com/fairDataSociety/fairdrive-landing-page/actions/runs/12380879860/job/34558194332#step:10:11)416ba12d400cd6d","historyAddress":""}
    at assertHexString (/home/runner/work/_actions/ethersphere/swarm-actions/latest/node_modules/@ethersphere/swarm-cid/dist/index.js:160:1)
    at assertReference (/home/runner/work/_actions/ethersphere/swarm-actions/latest/node_modules/@ethersphere/swarm-cid/dist/index.js:164:1)
    at _encodeReference (/home/runner/work/_actions/ethersphere/swarm-actions/latest/node_modules/@ethersphere/swarm-cid/dist/index.js:106:1)
    at encodeManifestReference (/home/runner/work/_actions/ethersphere/swarm-actions/latest/node_modules/@ethersphere/swarm-cid/dist/index.js:54:1)
    at Object.2917 (/home/runner/work/_actions/ethersphere/swarm-actions/latest/reference-to-cid/build/main.js:32:1)
    at __nccwpck_require__ (/home/runner/work/_actions/ethersphere/swarm-actions/latest/reference-to-cid/webpack/bootstrap:21:1)
    at /home/runner/work/_actions/ethersphere/swarm-actions/latest/reference-to-cid/webpack/startup:4:1
    at Object.<anonymous> (/home/runner/work/_actions/ethersphere/swarm-actions/latest/reference-to-cid/dist/index.js:28061:[12](https://github.com/fairDataSociety/fairdrive-landing-page/actions/runs/12380879860/job/34558194332#step:10:13))
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
```

**Comment by darkobas2** [comment]
Any update on this ?

**Comment by Cafe137** [comment]
> Any update on this ?

Working on Bee-JS version upgrade, addressing it there.
https://github.com/ethersphere/swarm-actions/pull/217

**Comment by Cafe137** [comment]
Fixed in #217
